spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQAo02MxDjkQaMb6G8hrVTgYXO/QdN5MG5/FlTiMRvqJW1VN+5KUY3e4kUSNFr37MFSYlQwgNMhEN/1g9JufUmMWdQS0hkfCpmR5JSM7d5TbW7qgJTgJ2pZOIEJOafcnZ+tgHoX/Rnd3zJqzjCFzU1ngoYuibtZdB/bVWl5Hh3cBt21UhwZdVtjM/4WON/FWz2h+dDus9gX18tT0eabWObFr53ZjHT7rNvS+bloEXcJR8XEGnRoxyowtl+Qo3ZRaI9IUdkKy4kz/w8UjJRmj6pM37wtJuA4Z6QlQa8iqpFcrN9ye6IJaGEMvH6k3FX28fWWEewrzdeEDFuRrQ+IT9Led+rfAOZSmOY+GuX6nFKIWBWF2RBPsukCoHRMMZhcTbUo='

token:
  expiration_time: 86600000
  secret: '{cipher}AQBVQXyf0xlGJgN/LVnT4aIA3dh8WAcH5/B7c9Eo9NEdqKqkGlGwXd1XTAmVfyHVoAK3mjMD8VwNhGjtntDXJ8hcrY6akrNQYadEz3bFjNQi+9PbGXJ2eORdPreKsp/pD/1jNjGsb92B23vUPfkwOAdnsZAeZJs2juO3LskvfS6nySIwLdtSpvOp56c0082vHaTbNXE+lqfi2cgGL+GinhOotKcGCIG0rgzdpsdF9wJwSiIwLn0qlfiL/PKgHmtunt6wjCSdiVH523MMNA5DOh3WigLzhElstJepV2dBgSZqZVNzbXf8msmU7AynkkeSsNn1auvvGEpFQAcXNKsAWy+50mzvrdCnjMxQwdk9uKX5wJKcqhWDISOSk3rHmLgW0YY='

gateway:
  ip: localhost

order_service:
  url: http://localhost:8000/order-service
